### ISSUE TITLE
Bandwidth reduction

### ISSUE THREAD

**Issue by kno10** [capnmidnight/Calla#103]
Bandwidth usage seems to be huge for many users.

It would be good if only nearby user and video streams are enabled.
Yes I am aware that this may require working with jitsi upstream to allow "muting" users. This is a wishlist issue.

**Comment by capnmidnight** [comment]
First of all, I strongly recommend against enabling video. It's only the because without it, people cousin constantly. But video does not really add anything useful to the experience.

As for the audio, the problem is that Jitsi is not peer to peer. You can't request a video stream from a specific user, you just get streams that the user has published to the room. Now, one could drop the audio stream from any other particular user, but there is no way to get it back again.

Jitsi isn't likely to implement such a feature. They're primary concern is in supporting their Jitsi Meet "Zoom-like" interface.

If I decide to continue to use Jitsi (and the jury is currently out, as there are some significant quality of life issue with using Jitsi that I won't go into right now), then the only way to do this would be to create a map-based interface for joining breakout rooms.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by kno10** [comment]
So you don't intend to continue using Jitsi?

**Comment by capnmidnight** [comment]
I don't know, I haven't definitively decided yet, and I'm nearing the end of pushing out a new project at work, so I don't have time to make such a big change right now.

But there is a bunch of stuff that Jitsi makes hard:

Obviously, this issue that you've brought up is not really possible to manage with the current version of Jitsi

It's really easy to end up with "ghost" users in Jitsi, people who didn't disconnect for whatever reason, leaving around user entries in Jitsi that aren't actually connected to anything. There is a heartbeat sensor that attempts to kill ghost users, but for some reason it doesn't always work and I'm left with just restarting the server as the only way I know how to deal with it.

Lib-jitsi-meet doesn't seem to expose a means for managing device access permissions, i.e. asking the user to give permission to use the mic and camera. It just does it on its own whenever you ask it for a list of devices. But you can't ask it for a list of devices until you connect to a session (I think this might be a bug), so there's kind of no way to let a user configure their devices before they join a session.

Lib-jitsi-meet is also extremely large. It ends up being about 70% of the bundle for the "game" app on the Calla website. It's about 90% of the "basic" app. Even my project at work, which creates a whole VR environment to move around in, is still at least 40% lib-jitsi-meet. This is concerning for me because I coveteth that memory for textures for objects in VR, which I'm running on some devices with somewhat limited resources. Indeed, having read some of the code for lib-jitsi-meet, it is my feeling that it is unreasonably large, that it just doesn't do enough to warrant that much code. And with the way that lib-jitsi-meet is written, there's no good way to include it in a tree-shaken bundle. Indeed, they expect you to load it directly from your Jitsi server, because releases of lib-jitsi-meet are tied to releases of Jitsi.

There are a lot of features in Jitsi that I *don't* need that are just there to support the Jitsi Meet app, like "dominant speaker detection". That's some amount of audio processing that is happening on the server that is not necessary for Calla.

Authenticating users before allowing them in a session is... IDK, maybe it's just not documented well. My cursory reading of it makes it sound insecure. Related to that, whomever is the first user to start a room always ends up Room Admin (with the ability to kick users, set room passwords, etc), regardless of whether or not you've setup authentication. So the way you're supposed to make sure that the right person ends up Room Admin is enable auth and not let lower level users create rooms. There's no built-in authorization mechanism, nor hooks to integrate with one.

In my project at work, I'd really like to have the media server running on the same box as the web and database servers. It would also help with improving the Calla instructions on how to set everything up. But I have yet to figure out how to do that, as Jitsi runs its own web server by default and the documentation on setting up Jitsi really only has two scenarios--the default installation and setting up everything from scratch, with big, bold warnings "you probably shouldn't try to do this" (setup from scratch).

Now, with the exception of Authentication, I've managed to mitigate most of these issues. But it makes for some difficulties, keeping track of all the little exceptions and hidden configuration options that I've had to set to get everything working right.
