### ISSUE TITLE
Only receive streams from people nearby

### ISSUE THREAD

**Issue by rponline** [capnmidnight/Calla#40]
This is a really fun project :) 
I would like to party with hundrets of people on one map.

To make this party scale up, users should just receive the videostreams from avatars nearby.
I don't know how hard this is to implement, but it would be a killer feature in my opinion.

**Comment by capnmidnight** [comment]
This would probably require finishing Issue #33 first. It's something I would implement as part of Issue #39 .

**Comment by capnmidnight** [comment]
Reopening this issue to think about it again.

The problem is, I don't think there is any way to control which streams are available, other than the room-level grouping. One could potentially attempt to do some K-means clustering to determine subgroups in the room and move people into "subrooms" (which would just be rooms, but auto-joined based on cluster membership). But leaving/joining a room is an expensive, laggy operation, and you would lose *all* visibility of other users in the process.

I think, if you get to a situation where you need to have hundreds of people in a continuous space, we'll need to split the environment into rooms that you can physically navigate between, aka Issue #35.
