### ISSUE TITLE
No effect?

### ISSUE THREAD

**Issue by paolobolzoni** [capnmidnight/Calla#44]
I am afraid I am missing something. I can see my friend's and my avatar on the map; but the volume is always the same. What are we supposed to do?

**Comment by capnmidnight** [comment]
What system/browser are you running? You should just have to walk around.

**Comment by paolobolzoni** [comment]
I am using Chromium in a recently updated Archlinux and I think my friend was using a similar setup. We tried both on a Jitsi server I installed on a Hetzner virtual machine and on the public square at https://www.calla.chat .

Basically, we could hear each other at the same way no matter where we were on the map.


Incidentally, in the installation instructions one reads `DOMAIN_NAME` but I think it was meant to be `JITSI_HOST`. Besides, I think to use the Jitsi server to distribute Calla files is actually _easier_ than set up a new server. If there is interest I can share the instructions.

**Comment by paolobolzoni** [comment]
Is there anything I can do test?

**Comment by capnmidnight** [comment]
I'm not sure what to suggest here. I can probably debug the issue on my own, but I had to take a short break from Calla because I spent too much time on it in April and May and need to get caught back up on my day job.

There might be an error message in the browser console that gives some more information. Unfortunately, Jitsi spams the console with a lot of messages. If you filter the message list down to just the Errors (no Info or Warnings), then you might be able to see something that looks like it's dealing with the WebAudio API. 

There are two errors that will immediately come up. The first is Jitsi will complain about there being "no analytics handler created". I disabled Google Analytics tracking, but don't know how to keep that error from showing up. The second is that it won't be able to load a file named "<room_name>.tmx". With Calla, you can define custom maps for named rooms, or if the file doesn't exist, it falls back to a default map.

When other users join, there will be an additional error per user: "Failed sending endpoint text message". This is because the Jitsi API does not have the WebRTC data channel open as soon as it gives the event that a user joined. So the only option is to just keep retrying to send state between users until it succeeds.

If any other errors show up, I'd be interested in seeing them.

**Comment by capnmidnight** [comment]
One of the reasons Calla is setup the way it is (with a separate server for Jitsi Meet and the game interface) is to minimize the number of changes I have to make to Jitsi. Ideally, I'd like to avoid making as many changes as possible. However, it looks like they put their lib-jitsi-meet connection objects into the global namespace, so I think there might be a chance I could make Calla inject itself into the standard Jitsi Meet install without having to make any changes to it, other than including a file.

Unfortunately, I don't know how to run Jitsi Meet on my local system to be able to test these changes.

**Comment by paolobolzoni** [comment]
I made few tests using the copy running in www.calla.chat . The console was indeed spammed with messages, but as far I could see there were no interesting errors.

With Chromium Calla was not working. Moving around had no effect.
In Firefox Calla was "kinda" working, but my friend and me we had to toggle the microphone Mute function few times in the beginning or we could have the fixed volume effect or not hear each other at all. However, once we stumbled upon random glitches like the avatar of one person disappearing.

I did not try with my own server yet, if I have a similar behavior I'll share the, very simple, installation instructions.

**Comment by capnmidnight** [comment]
I'm currently in the process of refactoring the entire code base to componentize and abstract the UI, game logic, and Jitsi integration away from each other. In the process, I discovered a few cases where certain messages between users were not being sent correctly. I believe these baldy formatted messages were causing some of the issues with avatars disappearing and settings not taking correctly.

In the process, I have also broke all audio scaling. So that's progress! (I consider an always-happening bug better than an intermittent bug).

I haven't deployed it yet as there are still some issues to work out, but the latest code in the matter branch is tracking the development.

**Comment by capnmidnight** [comment]
I've finished the majority of the refactoring. There's a new version on the site now that *hopefully* fixes some issues. I have audio spatialization working for me in Edge Chromium on Windows.

It doesn't address all potential issues, but it does make the code base a lot easier to comprehend now.

Still working on a few things and won't be closing this issue until those are complete. Specifically, the lib-jitsi-meet rewrite (which should be easier now that the game code and jitsi interfacing code are now completely separated).

**Comment by paolobolzoni** [comment]
Excellent, once you commit the few new things I'll be happy to try again. I am using video conferencing to play pen-n-paper role play games and the Calla functionality would be extremely useful.

About my installation with a single nginx server I went silent because after updating Calla without a discernible reason nginx started distributing all Calla files with the wrong Mime type. Since I really sure I did not anything about Mime the first time and it is better to try the new version anyhow I just gave up.

**Comment by capnmidnight** [comment]
The latest version on the site should be working pretty well right now.

**Comment by paolobolzoni** [comment]
I hate being the bearer of unhelpful bad news... but the test with Chromium on Linux gave basically the starting results. After playing around with the microphone (like changing microphone, toggle the on/off, ...) we could hear each other. But the volume was fixed.
I'll see if I can try with Firefox on Linux soon.

**Comment by capnmidnight** [comment]
I've been unable to test this as I'm somewhat between computers right now and my current desktop won't even run Linux in a VM properly. 

It might be that the fact that all the audio code runs in an IFrame means that the AudioContext is not allowed to start. On some systems, you have to have a direct user-interaction event (a button click, or something) and create the AudioContext from within the event handler, for the WebAudio API to be allowed to work. With the original implementation of Calla using the Jitsi External API, that meant that there was never a "user interaction" event that could trigger the creation of the AudioContext, defaulting to using just the regular HTML Audio elements to run the audio interface.

I just released a new version that completely re-implements that application for using a different API for Jitsi. This API allows embedding Jitsi directly in the page, rather than in an IFrame. Perhaps this fixes the issue?

**Comment by capnmidnight** [comment]
@paolobolzoni any chance you've had/have time to test this? I'm still in the process of scaring up a Linux system.

**Comment by paolobolzoni** [comment]
I could finally test a bit.

Chromium still worked badly, my friend could not hear me but I could hear him properly. By properly I mean with the volume and stereo changing depending on the map position. Besides, the emoji were in text mode with many missing.
Firefox instead worked well.

However, I am missing how to go back to the normal jitsi interface, or at least being able to see the video stream large. It seems kinda pointless to send 500kB/s of video stream to see only a stamp sized preview.

**Comment by capnmidnight** [comment]
The normal Jitsi interface is gone forever.
